name: 'Check build'
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: yarn build